@echo off
echo Installiere Abhaengigkeiten...
pip install -r requirements.txt
echo Starte FastAPI Server...
start http://localhost:8000/docs
python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
